// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwwW0eTerKAwwGClZ8cKufDhQBzuCfWE8',
    appId: '1:133553272540:web:ce720e76ebf70f1229a619',
    messagingSenderId: '133553272540',
    projectId: 'artgen-66569',
    authDomain: 'artgen-66569.firebaseapp.com',
    storageBucket: 'artgen-66569.appspot.com',
    measurementId: 'G-62BCBRFXDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuNxjIULeWbQuF1xfCbYUuYBBLmC8tWbU',
    appId: '1:133553272540:android:093d1219433c415729a619',
    messagingSenderId: '133553272540',
    projectId: 'artgen-66569',
    storageBucket: 'artgen-66569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLk5Sk6iUrOnR-rDNxgUoWFxhkHWwTfqM',
    appId: '1:133553272540:ios:42d2d0f705dcbd3329a619',
    messagingSenderId: '133553272540',
    projectId: 'artgen-66569',
    storageBucket: 'artgen-66569.appspot.com',
    iosClientId:
        '133553272540-lsvdah19pjatietpecghlph2qv4gdh0h.apps.googleusercontent.com',
    iosBundleId: 'com.enginosoft.artgen',
  );
}
